# Generated by Django 5.0.3 on 2024-05-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
