# Generated by Django 5.0.3 on 2024-07-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_useraccount_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='total_points',
        ),
    ]
