# Generated by Django 5.0.3 on 2024-07-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useraccount_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
