# Generated by Django 5.0.3 on 2024-07-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_level_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='quiz.level'),
        ),
    ]
