# Generated by Django 5.0.3 on 2024-07-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderoard',
        ),
    ]
